## Sistem Persamaaan Linear

Persamaan linear adalah persamaan matematika yang menggambarkan hubungan linear antara variabel-variabelnya. Secara umum, persamaan linear dapat ditulis dalam bentuk:

$ y=mx+by=mx+b $

di mana $y$ adalah variabel dependen, $x$ adalah variabel independen, $m$ adalah kemiringan (slope), dan $b$ adalah perpotongan dengan sumbu $y$ (y-intercept). Persamaan ini menggambarkan garis lurus pada bidang Cartesius. Dalam konteks yang lebih umum, persamaan linear dapat memiliki lebih dari satu variabel dan dapat diwakili dalam bentuk umum:

$a_1x_1+a_2x_2+…+a_nx_n=b$

di mana $a_1,a_2,…,a_n​$ adalah koefisien, $x_1,x_2,…,x_n$​ adalah variabel-variabel, dan bb adalah konstanta. Persamaan linear ini bisa menggambarkan hubungan linear antara lebih dari satu variabel.

### Contoh persamaan linear


In [1]:
import numpy as np
A=np.array([[8,9,1,19],[1,2,3,9],[2,1,1,5]])

In [2]:
print(A)

[[ 8  9  1 19]
 [ 1  2  3  9]
 [ 2  1  1  5]]


Jadi, ketiga persamaan linier tiga variabel diatas adalah sebagai berikut

$ 8x_1 + 9x_2 + x_3 = 19 $

$ x_1 + 2x_2 + 3x_3 = 9 $

$ 2x_1 + x_2 + x_3 = 5 $

## Eliminasi Gauss

Eliminasi Gauss adalah metode yang digunakan dalam aljabar linier untuk menyelesaikan sistem persamaan linear. Tujuannya adalah untuk mentransformasi sistem persamaan linear menjadi bentuk yang lebih sederhana, yang memudahkan untuk menemukan solusi sistem tersebut.

Langkah-langkah eliminasi Gauss adalah sebagai berikut:

1. **Pemilihan Pivot**: Pilih elemen non-nol pertama dari baris pertama, yang disebut sebagai elemen pivot. Ini biasanya elemen pertama yang bukan nol.

2. **Operasi Baris**: Gunakan elemen pivot untuk membuat nol semua elemen di bawahnya dalam kolom yang sama. Ini dilakukan dengan mengurangi kelipatan dari baris pivot dari baris-baris di bawahnya.

3. **Iterasi**: Langkah operasi baris di atas diulang untuk setiap baris, dimulai dari baris kedua, ketiga, dan seterusnya.

Setelah langkah-langkah di atas dilakukan, sistem persamaan linear akan berada dalam bentuk segitiga atas (upper triangular form). Dalam bentuk ini, mudah untuk menemukan solusi sistem menggunakan metode substitusi atau metode balikan (backward substitution).


### contoh penerapan eliminasi Gauss

Untuk penerapan eliminasi Gauss, saya kita bisa mengambil contoh persamaan linier yang diatas


$ 8x_1 + 9x_2 + x_3 = 19 $

$ x_1 + 2x_2 + 3x_3 = 9 $

$ 2x_1 + x_2 + x_3 = 5 $

Pertama-tama kita menulis kode program untuk digunakan pada perhitungan persamaan linier dengan cara eliminasi Gauss

In [3]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

Setelah menulis kode program tersebut, kita mendapatkan tiga fungsi, yaitu **RowSwap**,**RowScale**, dan **RowAdd**. Setelah itu, kita terapkan pada persamaan yang telah kita tulis diatas

1. **RowSwap** adalah fungsi yang menukarkan posisi dua baris dari suatu matriks 
2. **RowScale** adalah fungsi yang mengalikan suatu baris dalam matriks dengan konstanta dengan nilai konstanta tidak sama dengan nol 
3. **RowAdd** adalah fungsi yang menambahkan kelipatan suatu baris dengan baris yang lain

Tahap pertama, yaitu menukar posisi persamaan ke-1 dengan persamaan ke-2 dengan fungsi **RowSwap**

In [4]:
A1 = RowSwap(A,0,1) #index python dimulai dari 0,1,2, dan seterusnya
print(A1)

[[ 1.  2.  3.  9.]
 [ 8.  9.  1. 19.]
 [ 2.  1.  1.  5.]]


Tahap kedua yaitu menambahkan -8 kali persamaan ke-1 ke persamaan ke-2 dengan fungsi **RowAdd**

In [5]:
A2 = RowAdd (A1,0,1,-8)
print(A2)

[[  1.   2.   3.   9.]
 [  0.  -7. -23. -53.]
 [  2.   1.   1.   5.]]


Tahap ketiga yaitu menambahkan -2 kali persamaan ke-1 ke persamaan ke-3

In [6]:
A3 = RowAdd(A2,0,2,-2)
print(A3)

[[  1.   2.   3.   9.]
 [  0.  -7. -23. -53.]
 [  0.  -3.  -5. -13.]]


Tahap keempat yaitu mengalikan persamaan ke-2 dengan 1/7 dengan fungsi **RowScale**

In [7]:
A4 = RowScale(A3,1,-1/7)
print(A4)

[[  1.           2.           3.           9.        ]
 [ -0.           1.           3.28571429   7.57142857]
 [  0.          -3.          -5.         -13.        ]]


Tahap kelima yaitu menambahkan 3 kali persamaan ke-2 ke persamaan ke-3

In [8]:
A5 = RowAdd(A4,1,2,3)
print(A5)

[[ 1.          2.          3.          9.        ]
 [-0.          1.          3.28571429  7.57142857]
 [ 0.          0.          4.85714286  9.71428571]]


Tahap keenam yaitu mengalikan persamaan-3 dengan 1/4.85714286 (agar nilai $x_3$ persamaan ke-3 bernilai 1)

In [9]:
A6 = RowScale(A5,2,1/4.85714286)
print(A6)

[[ 1.          2.          3.          9.        ]
 [-0.          1.          3.28571429  7.57142857]
 [ 0.          0.          1.          2.        ]]


Setelah dilakukan penghitungan akan didapatkan persamaan sebagai berikut


$ x_1 + 2x_2 + 3x_3 = 9$

$x_2 + 3.28571429x_3 = 7.57142857$

$x_3 = 2 $

Maka, bisa didapat bahwa nilai dari $x_3$ adalah $2$. Dengan begitu kita bisa mencari nilai $x_1$ dan $x_2$ dengan cara substitusi sebagai berikut

In [10]:
x3 = 2
x2 = 7.57142857 - (3.28571429 * x3)
print ('X2 =', round(x2))

X2 = 1


In [11]:
x1 = 9 - ((round(x2) * 2) + (x3 * 3))
print (x1)

1


Jadi, bisa didapat nilai dari $x_1$, $x_2$, dan $x_3$ sebagai berikut 

$ x_1 = 1\\
  x_2 = 1\\
  x_3 = 2\\
  $

Contoh persamaan yang lain dengan menggunakan 4 variabel

$ 2x_1 + 3x_2 - x_3 + 4x_4 = 10 $ 

$ x_1 −2x_2 + 4x_3 − 3x_4 = 5 $

$ 3x_1 + x_2 + 2x_3 − 2x_4 = 7 $

$ 4x_1 − x_2 − x_3 + 2x_4 = 8 $

Persamaan diatas akan saya selesaikan menggunakan eliminasi Gauss

In [12]:
import numpy as np
B = np.array([[2,3,-1,4,10],[1,-2,4,-3,5],[3,1,2,-2,7],[4,-1,-1,2,8]])
print(B)

[[ 2  3 -1  4 10]
 [ 1 -2  4 -3  5]
 [ 3  1  2 -2  7]
 [ 4 -1 -1  2  8]]


In [13]:
B1 = RowSwap(B,0,1)
print(B1)

[[ 1. -2.  4. -3.  5.]
 [ 2.  3. -1.  4. 10.]
 [ 3.  1.  2. -2.  7.]
 [ 4. -1. -1.  2.  8.]]


In [14]:
B2 = RowAdd(B1,0,1,-2)
print(B2)

[[ 1. -2.  4. -3.  5.]
 [ 0.  7. -9. 10.  0.]
 [ 3.  1.  2. -2.  7.]
 [ 4. -1. -1.  2.  8.]]


In [15]:
B3 = RowAdd(B2,0,2,-3)
print(B3)

[[  1.  -2.   4.  -3.   5.]
 [  0.   7.  -9.  10.   0.]
 [  0.   7. -10.   7.  -8.]
 [  4.  -1.  -1.   2.   8.]]


In [16]:
B4 = RowAdd(B3,0,3,-4)
print(B4)

[[  1.  -2.   4.  -3.   5.]
 [  0.   7.  -9.  10.   0.]
 [  0.   7. -10.   7.  -8.]
 [  0.   7. -17.  14. -12.]]


In [17]:
B5 = RowScale(B4,1,1/7)
print(B5)

[[  1.          -2.           4.          -3.           5.        ]
 [  0.           1.          -1.28571429   1.42857143   0.        ]
 [  0.           7.         -10.           7.          -8.        ]
 [  0.           7.         -17.          14.         -12.        ]]


In [18]:
B6 = RowAdd(B5,1,2,-7)
print(B6)

[[  1.          -2.           4.          -3.           5.        ]
 [  0.           1.          -1.28571429   1.42857143   0.        ]
 [  0.           0.          -1.          -3.          -8.        ]
 [  0.           7.         -17.          14.         -12.        ]]


In [19]:
B7 = RowAdd(B6,1,3,-7)
print(B7)

[[  1.          -2.           4.          -3.           5.        ]
 [  0.           1.          -1.28571429   1.42857143   0.        ]
 [  0.           0.          -1.          -3.          -8.        ]
 [  0.           0.          -8.           4.         -12.        ]]


In [20]:
B8 = RowAdd(B7,2,3,-8)
print(B8)

[[ 1.         -2.          4.         -3.          5.        ]
 [ 0.          1.         -1.28571429  1.42857143  0.        ]
 [ 0.          0.         -1.         -3.         -8.        ]
 [ 0.          0.          0.         28.         52.        ]]


Dengan begini kita bisa menemukan nilai dari $x_4$ yaitu $\frac{52}{28}$ atau $\frac{13}{7}$

Setelah itu, kita bisa mencari nilai $x_1, x_2,$ dan $x_3$ dengan substitusi mundur

$-x_3 - 3x_4 = -8$ \
$x_3 + 3x_4 = 8$

In [21]:
x4 = 13/7
x3 = 8 - (x4*3)
print(x3)
print(x4)
print(x3*7)
print(x4*7)

2.428571428571429
1.8571428571428572
17.0
13.0


$x_3 = \frac{17}{7}$

$ x_2 - 1.28571429x_3 + 1.42857143x_4 = 0$ (dikali 7) \
$ 7x_2 - 9x_3 + 10x_4 = 0 $

In [22]:
x3 = 2.428571428571429
x4 = 1.8571428571428572
x2 = (1.28571429 * x3) - (1.42857143 * x4)
print(x2)
print(x2*49)

0.469387762857143
23.000000380000007


$x_2 = \frac{23}{49}$

$x_1 - 2x_2 + 4x_3 - 3x_4 = 5$

In [23]:
x1 = 5 + 2*x2 - 4*x3 + 3*x4
print(x1)
print(x1*49)

1.795918382857142
88.00000075999995


Jadi, nilai dari $x_1, x_2, x_3, x_4$ adalah $ \frac{88}{49} $, $ \frac{23}{49}$, $\frac{17}{7}$, $\frac{13}{7}$ 