# Aljabar Matriks

Matriks adalah suatu susunan bilangan real atau bilangan kompleks (atau elemen-elemen) yang disusun dalam baris dan kolom sehingga membentuk jajaran persegi panjang. Suatu matriks diberi nama dengan menggunakan huruf kapital seperti A, B, C, dan seterusnya, sedangkan anggotanya dinyatakan dengan huruf kecil.

Kita bisa membuat matriks di python dengan fungsi np.array yang nilainya bisa diisi sendiri

In [39]:
import numpy as np
A = np.array ([[1, 3, 4], [2, 1, 5]])
B = np.array ([[3, 0, 4], [-1, -2, -1]])
C = np.array ([[2, 8, 7], [6, 5, 2]])
D = np.array ([[12, 4]])
print(A)
print(B)
print(C)
print(D)

[[1 3 4]
 [2 1 5]]
[[ 3  0  4]
 [-1 -2 -1]]
[[2 8 7]
 [6 5 2]]
[[12  4]]


Atau kita bisa membuat matriks dengan fungsi random dengan ukuran yang bisa ditentukan sendiri ,contoh matriks ukuran 3x3

In [40]:
A = np.random.randint(10, size=(3,3))
print(A)

[[5 1 0]
 [9 7 8]
 [8 7 4]]


## Operasi Bilangan Matriks

### Penjumlahan Matriks

Penjumlahan Matriks pada dasarnya sama dengan penjumlahan bilangan, namun dengan salah satu syarat yaitu matriks yang dijumlahkan memiliki ordo yang sama. contohnya matriks $A$ dengan ordo 2x2 dijumlahkan dengan matriks $B$ dengan ordo 2x2 atau matriks $C$ dengan ordo 3x3 dijumlahkan dengan matriks $D$ dengan ordo 3x3    

Berikut Sifat sifat Penjumlahan Matriks


1. Sifat komutatif.
Pada sifat ini berlaku A + B = B + A.

2. Sifat asosiatif.
Pada sifat ini berlaku (A + B) + C = A +(B + C)

3. Matriks nol.
Pada sifat ini berlaku A + 0 = A.

4. Jika dijumlahkan dengan lawannya akan menghasilkan matriks nol, yaitu A + (-A) = 0. 


Contoh penjumlahan matriks

$\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}$
+
$\begin{bmatrix}
2 & 4\\
6 & 8
\end{bmatrix}$
::
$\begin{bmatrix}
3 & 6\\
9 & 12
\end{bmatrix}$

### Perkalian Matriks

Perkalian pada Matriks terbagi menjadi 2, yaitu perkalian matriks dengan konstanta dan perkalian antarmatriks 

#### 1. Perkalian Matriks dengan Konstanta
Adalah suatu operasi yang mengalikan matriks dengan suatu nilai konstanta

Contoh perkalian Matriks dengan Konstanta:
Matriks M
$\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}$
dikalikan dengan konstanta bernilai 5

In [41]:
M = np.array([[1,2], [3,4]])
print(M)
N = M * 5
print(N)

[[1 2]
 [3 4]]
[[ 5 10]
 [15 20]]


Hasilnya adalah Matriks N
$\begin{bmatrix}
5 & 10\\
15 & 20
\end{bmatrix}$

#### 2. Perkalian AntarMatriks

Adalah Operasi yang mengalikan matriks dengan matriks lainnya salah satu syarat perkalian antarmatriks adalah kolom matriks yang mengalikan sama dengan
baris matriks yang dikalikan

Contoh perkalian antarmatriks

In [42]:
#menentukan matriks yang akan dikalikan
A = np.random.randint(10, size=(2,3))
B = np.random.randint(10, size=(3,2))
print(A)
print(B)

[[5 1 7]
 [0 6 9]]
[[7 3]
 [4 2]
 [4 0]]


In [43]:
#melakukan operasi perkalian matriks
C = np.dot(A,B)
print(C)
D = A.dot(B)
print(D)

[[67 17]
 [60 12]]
[[67 17]
 [60 12]]


# Matriks Transpose

In [44]:
A = np.array([[5, 4, 0],[1,8,3],[6,7,2]])
A_T = A.transpose()
print(A)
print('\n')
print(A_T)

[[5 4 0]
 [1 8 3]
 [6 7 2]]


[[5 1 6]
 [4 8 7]
 [0 3 2]]


In [45]:
C = A * A_T
C_T = C.transpose()
COV = C * C_T
print(COV)
print(COV.shape)

[[ 625   16    0]
 [  16 4096  441]
 [   0  441   16]]
(3, 3)


In [46]:
A = np.array([[2,1],[1,2]])
A_T = A.transpose()
print(A)
print(A_T) 

[[2 1]
 [1 2]]
[[2 1]
 [1 2]]


In [47]:
M = np.array ([[10, 3, 5], [3, 7, 9], [5, 9, 12]])
M_T = M.transpose()
print(M)
print(M_T)

[[10  3  5]
 [ 3  7  9]
 [ 5  9 12]]
[[10  3  5]
 [ 3  7  9]
 [ 5  9 12]]


In [48]:
A = np.random.randint(10, size=(3,3))
B = np.random.randint(10, size=(3,3))
D = np.random.randint(10, size=(3,3))
E = (( A + B) * C)
F = E.transpose()
print(A)
print(B)
print(C)
print(E)
print(F)


[[6 3 3]
 [0 6 9]
 [9 1 3]]
[[4 6 3]
 [1 2 5]
 [6 4 2]]
[[25  4  0]
 [ 4 64 21]
 [ 0 21  4]]
[[250  36   0]
 [  4 512 294]
 [  0 105  20]]
[[250   4   0]
 [ 36 512 105]
 [  0 294  20]]


# Matriks Elementer

# Matriks Invers

In [49]:
A = np.array([[2,1],[1,1]])
B = np.array([[1,0],[1,1]])
print(A*B)
print(B*A)

[[2 0]
 [1 1]]
[[2 0]
 [1 1]]


In [50]:
A = np.array([[2,2,1],[4,2,3],[1,3,-1]])
print(A)

[[ 2  2  1]
 [ 4  2  3]
 [ 1  3 -1]]


In [51]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [52]:
A1 = RowSwap(A,0,2)
print(A1)

[[ 1.  3. -1.]
 [ 4.  2.  3.]
 [ 2.  2.  1.]]


In [53]:
A2 = RowAdd(A1,0,1,-4)
print(A2)

[[  1.   3.  -1.]
 [  0. -10.   7.]
 [  2.   2.   1.]]


In [54]:
A3 = RowAdd(A2,0,2,-2)
print(A3)

[[  1.   3.  -1.]
 [  0. -10.   7.]
 [  0.  -4.   3.]]


In [55]:
A4 = RowSwap(A3,1,2)
print(A4)

[[  1.   3.  -1.]
 [  0.  -4.   3.]
 [  0. -10.   7.]]


In [56]:
A5 = RowAdd(A4,1,2,-2)
print(A5)

[[ 1.  3. -1.]
 [ 0. -4.  3.]
 [ 0. -2.  1.]]


In [57]:
A6 = RowAdd(A5,2,0,1)
print(A6)

[[ 1.  1.  0.]
 [ 0. -4.  3.]
 [ 0. -2.  1.]]


In [58]:
A7 = RowAdd(A6,2,1,-3)
print(A7)

[[ 1.  1.  0.]
 [ 0.  2.  0.]
 [ 0. -2.  1.]]


In [59]:
A8= RowAdd(A7,1,0,-0.5)
print(A8)

[[ 1.  0.  0.]
 [ 0.  2.  0.]
 [ 0. -2.  1.]]


In [60]:
A9 = RowScale(A8,1,1/2)
print(A9)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -2.  1.]]


In [64]:
A10 = RowAdd(A9,1,2,2)
print(A10)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [65]:
B = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(B)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [66]:
B1 = RowSwap(B,0,2)
print(B1)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [67]:
B2 = RowAdd(B1,0,1,-4)
print(B2)

[[ 0.  0.  1.]
 [ 0.  1. -4.]
 [ 1.  0.  0.]]


In [68]:
B3 = RowAdd(B2,0,2,-2)
print(B3)

[[ 0.  0.  1.]
 [ 0.  1. -4.]
 [ 1.  0. -2.]]


In [69]:
B4 = RowSwap(B3,1,2)
print(B4)

[[ 0.  0.  1.]
 [ 1.  0. -2.]
 [ 0.  1. -4.]]


In [70]:
B5 = RowAdd(B4,1,2,-2)
print(B5)

[[ 0.  0.  1.]
 [ 1.  0. -2.]
 [-2.  1.  0.]]


In [71]:
B6 = RowAdd(B5,2,0,1)
print(B6)

[[-2.  1.  1.]
 [ 1.  0. -2.]
 [-2.  1.  0.]]


In [72]:
B7 = RowAdd(B6,2,1,-3)
print(B7)

[[-2.  1.  1.]
 [ 7. -3. -2.]
 [-2.  1.  0.]]


In [73]:
B8= RowAdd(B7,1,0,-0.5)
print(B8)

[[-5.5  2.5  2. ]
 [ 7.  -3.  -2. ]
 [-2.   1.   0. ]]


In [75]:
B9 = RowScale(B8,1,1/2)
print(B9)


[[-5.5  2.5  2. ]
 [ 3.5 -1.5 -1. ]
 [-2.   1.   0. ]]


In [76]:
B10 = RowAdd(B9,1,2,2)
print(B10)

[[-5.5  2.5  2. ]
 [ 3.5 -1.5 -1. ]
 [ 5.  -2.  -2. ]]


In [ ]:
C = RowSwap(,0,2)
print(1)
B2 = RowAdd(B1,0,1,-4)
print(B2)
B3 = RowAdd(B2,0,2,-2)
print(B3)
B4 = RowSwap(B3,1,2)
print(B4)
B5 = RowAdd(B4,1,2,-2)
print(B5)

