# Eigen Value & Eigen Vector

## Konsep Eigen Value dan Eigen Vektor
Apabila ada sebuah matriks A maka vektor tak nol yang tak nol yang dilambangkan vektor $x$ dinamakan eigen vector (vektor eigen) dari A, dan jika $Ax$ merupakan kelipatan skalar dari $x$ yakni $Ax = \lambda x$ maka skalar $\lambda$ merupakan eigen value (nilai eigen) dari A dan x dikatakan eigen vektor yang bersesuaian dengan skalar $\lambda$

## Contoh menghitung Eigen Value dan Eigen Vektor menggunakan fungsi Numpy pada python
Misal terdapat matriks $A_{2 \times 2}$ sebagai berikut

$ A =
\begin {bmatrix}
1 & 4 \\
3 & 2 
\end {bmatrix}$

Cara menghitung eigen value dan eigen vector dari matriks $A$ diatas apabila menggunakan Numpy adalah sebagai berikut

In [2]:
import numpy as np
A = np.array([[1,4],[3,2]])
egval, egvec = np.linalg.eig(A)
print(np.round(egval))
print(np.round(egvec))

[-2.  5.]
[[-1. -1.]
 [ 1. -1.]]


Bisa didapatkan eigen value dari matriks $A$ adalah $\begin {bmatrix} -2 & 5 \end {bmatrix}$ dan eigen vectornya adalah $\begin {bmatrix} -1 & -1 \\ 1 & -1 \end {bmatrix}$ 

Apabila menggunakan sampel matriks $3 \times 3$ adalah sebagai berikut

$A =
\begin {bmatrix}
1 & 4 & 2 \\
2 & 1 & 1 \\
3 & 2 & 1
\end {bmatrix}$

In [3]:
A = np.array ([[1,4,2],[2,1,1],[3,2,1]])
egval, egvec = np.linalg.eig(A)
print("Nilai eigen value = ", np.round(egval, decimals = 1))
print("Nilai eigen vector = ", np.round(egvec, decimals = 1))

Nilai eigen value =  [ 5.5 -2.1 -0.4]
Nilai eigen vector =  [[ 0.7  0.8 -0.2]
 [ 0.4 -0.3 -0.4]
 [ 0.6 -0.5  0.9]]


Maka bisa didapat eigen valuenya adalah $\begin {bmatrix} 5.5 & -2.1 & -0.4 \end {bmatrix}$ dan eigen vectornya adalah $\begin {bmatrix} 0.7 & 0.8 & -0.2 \\ 0.4 & -0.3 & -0.4 \\ 0.6 & -0.5 & 0.9 \end {bmatrix}$

## Implementasi Eigen Value dan Eigen Vector

In [4]:
import numpy as np


def pcaEVD(X):
    # Center X and get covariance matrix C
    n, p = X.shape
    X -= X.mean(axis=0)
    C = (X.T@X) / (n-1)

    # EVD
    e_vals, e_vecs = np.linalg.eig(C)
    idx = e_vals.argsort()[::-1]   
    e_vals = e_vals[idx]
    e_vecs = e_vecs[:, idx]

    # Return principal compnents and eigenvalues to calculate the portion of sample variance explained
    return (X @ e_vecs), e_vals

def pcaSVD(X):
    # Center X and get covariance matrix C
    n, p = X.shape
    X -= X.mean(axis=0)

    # SVD
    u, sigma, vt = np.linalg.svd(X, full_matrices=False)

    # Return principal compnents and eigenvalues to calculate the portion of sample variance explained
    return (X @ vt.T), (sigma**2) / (n-1)



Pada fungsi pcaEVD, mean dari setiap kolom matriks $X$ dikurangi sehingga data menjadi terpusat (mean dari setiap kolom adalah nol). Kemudian matriks kovarians $C$ dihitung dengan mengalikan matriks transpose $X$ dengan $X$, lalu dibagi dengan n-1. Setelah itu, dilakukan dekomposisi matriks kovarian $C$ yang menghasilkan nilai eigen (e_vals) dan vektor eigen (e_vecs). Nilai eigen diurutkan secara menurun, dan vektor eigen diurutkan sesuai dengan urutan nilai eigen. Setelah itu, Komponen utama diperoleh dengan mengalikan $X$ dengan vektor eigen yang diurutkan. Fungsi ini mengembalikan komponen utama dan nilai eigen yang menjelaskan proporsi variansi sampel.



Pada fungsi pcaSVD, Sama seperti pada pcaEVD, data dipusatkan dengan mengurangi mean dari setiap kolom dalam X. Kemudian, dilakukan dekomposisi nilai singular pada X, menghasilkan matriks u, sigma, dan vt. Matriks u adalah matriks ortogonal, sigma adalah vektor nilai singular, dan vt adalah transpose dari matriks vektor singular kanan. Komponen utama diperoleh dengan mengalikan X dengan transpose dari vt. Nilai eigen dihitung sebagai kuadrat dari nilai singular (sigma) dibagi dengan n-1 Fungsi ini mengembalikan komponen utama dan nilai eigen yang menjelaskan proporsi variansi sampel.



In [ ]:
import matplotlib.pyplot as plt
from matplotlib.font_manager import FontProperties


TITLE_FONT = FontProperties(family="Arial", size=16, weight="semibold")
AXIS_FONT = FontProperties(family="Arial", size=14)
LASALLE_BLUE = "#00245D"

# Get feature names
feature_names = [" ".join(name.split(" ")[:-1])
                 for name in iris['feature_names']]
p = vt.shape[0]
pc_labels = ["PC %s" % (i+1) for i in range(p)]

# Calculate proportion of variance explained
eig_val = sigma**2 / (X_.shape[0]-1)
ve = eig_val / eig_val.sum()

plt.figure(figsize=(20, 10), dpi=200)

# Plot proportion of total variance explained
plt.subplot(1, 2, 1)
plt.plot(range(p), ve, 'o-', c=LASALLE_BLUE)
plt.title("Proportion of Total Variance Explained (Centered)", fontproperties=TITLE_FONT)
plt.xticks(range(p), pc_labels, fontproperties=AXIS_FONT)
plt.ylim(0, 1)

# Plot factor loadings
plt.subplot(1, 2, 2)
plt.matshow(vt*np.sqrt(eig_val), cmap="coolwarm", fignum=False)
plt.title("Factor Loadings (Centered)", fontproperties=TITLE_FONT)
plt.yticks(range(p), pc_labels, fontproperties=AXIS_FONT)
plt.xticks(range(p), feature_names, fontproperties=AXIS_FONT)
plt.tick_params(axis='both', length=0.5, direction='out')
for (i, j), z in np.ndenumerate(vt*np.sqrt(eig_val)):
    plt.text(j, i, '{:0.2f}'.format(z), ha='center', va='center',
             fontproperties=AXIS_FONT)