# Determinan
Determinan adalah skalar dari suatu matriks



In [1]:
import numpy as np
A =np.array([[1 , 2],[3 , 4]])
B = np.array([[2, 3, 5],[8, 4, 7],[6, 9, 1]])
print(A)
print(B)

[[1 2]
 [3 4]]
[[2 3 5]
 [8 4 7]
 [6 9 1]]


## Sifat-sifat determinan
Sifat-sifat Determinan adalah sebagai berikut:
1. Determinan matriks identitas sama dengan $1$ \
  Jadi $I × I^{-1} = 1$\
  Contoh :\
  $I_{2 \times 2} = \begin {bmatrix}
0 & 1 \\
1 & 0
\end {bmatrix}$\
$I_{3 \times 3} = \begin {bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end {bmatrix}$\
$I = AA^{-1}$\
$det I = det A × det A^{-1}$\
$det A = 1 \div det A^{-1}$


In [2]:
I= np.array([[1,0],[0,1]])
L= np. array([[1,0,0],[0,1,0],[0,0,1]])
print(I)
print(L)

[[1 0]
 [0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [3]:
C = np.linalg.inv(A)
D = np.linalg.inv(B)
E = 1/np.linalg.det(A)
F = 1/np.linalg.det(B)
print(np.linalg.det(A))
print(np.linalg.det(B))
print(np.linalg.det(I))
print(C)
print(D)
print(E)
print(F)

-2.0000000000000004
223.99999999999994
1.0
[[-2.   1. ]
 [ 1.5 -0.5]]
[[-2.63392857e-01  1.87500000e-01  4.46428571e-03]
 [ 1.51785714e-01 -1.25000000e-01  1.16071429e-01]
 [ 2.14285714e-01 -2.97381167e-18 -7.14285714e-02]]
-0.4999999999999999
0.004464285714285716


In [4]:
# import library numpy
import numpy as np

def RowSwap(A,k,l):
# =============================================================================
#     A adalah sebuah NumPy array.  RowSwap akan menghasilkan duplicate dari
#     array dengan baris k dan l di tukar
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowScale akan menghasilkan duplicate dari
#     array dengan baris k di kali dengan skalar bukan 0
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowAdd akan menghasilkan duplicate dari
#     array dengan baris k akan di kali dengan 'scale' bukan 0. lalu nilai
#     baris l akan di tambah dengan nilai baris k yang sudah dikalikan
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

2. Determinan $AB$ = $det A × det B$\


In [5]:
A = np.array([[1,4,2],[1,1,1],[3,2,1]])
D = np.linalg.det(A)
print(A)
print(round(D))

[[1 4 2]
 [1 1 1]
 [3 2 1]]
5


Menukar baris pada matriks dapat mengubah tanda determinan

In [6]:
A1 = np.array([[1,1,1],[1,4,2],[3,2,1]])
D1 = np.linalg.det(A1)
print(A1)
print(round(D1))

[[1 1 1]
 [1 4 2]
 [3 2 1]]
-5


Mengubah kolom matriks dapat mengubah tanda determinan

In [7]:
A2 = np.array([[4,1,2],[1,1,1],[2,3,1]])
D2 = np.linalg.det(A2)
print(A2)
print(round(D2))

[[4 1 2]
 [1 1 1]
 [2 3 1]]
-5


3. Apabila bilangan bilangan suatu baris yang mana kelipatan dari baris yang lain maka determinannya sama dengan nol

In [8]:
B = np.array ([[1,4,2],[2,8,4],[3,2,1]])
D3 = np.linalg.det(B)
print(B)
print(D3)

[[1 4 2]
 [2 8 4]
 [3 2 1]]
0.0


4. Apabila bilangan-bilangan suatu kolom pada matriks merupakan kelipatan dari kolom yang lain maka determinannya sama dengan nol  

In [9]:
C = np.array([[1,4,2],[2,8,3],[1,4,1]])
D4 = np.linalg.det(C)
print(C)
print(D4)

[[1 4 2]
 [2 8 3]
 [1 4 1]]
0.0


5. Apabila ada sebuah skalar misal $K$ dikali dengan matriks A
maka $det(KA) = K^n det(A)$ yang mana $n$ adalah ukuran dari matriks\
$A = \begin {bmatrix}
1 & 4 & 2 \\
1 & 1 & 1 \\
3 & 2 & 1
\end {bmatrix}$ \
$K = 2$ \
$KA = 2 \begin{bmatrix}
1 & 4 & 2 \\
1 & 1 & 1 \\
3 & 2 & 1
\end{bmatrix} $

In [10]:
A = np.array ([[1,4,2],[1,1,1],[3,2,1]])
K = 2
n = 3
KA = K**n * np.linalg.det(A)
print(round(KA))

40


6. Apabila suatu baris matriks $B$ adalah kelipatan dari suatu baris matriks $A$ maka determinan matriks $B$ adalah kelipatan dari determinan matriks $A$

In [14]:
A = np.array([[1,4,2],[1,1,1],[3,2,1]])
B = np.array([[2,8,4],[1,1,1],[3,2,1]])
dA = np.linalg.det(A)
dB = np.linalg.det(B)
print(round(dA))
print(round(dB))

5
10


7. Apabila terdapat suatu matriks segitiga atas maka determinannya adalah hasil dari perkalian elemen elemen diagonal utamanya
Contoh matriks $A = \begin {bmatrix}
1 & 4 & 2 \\
0 & 4 & 1 \\
0 & 0 & 1
\end {bmatrix}$

In [15]:
A = np.array([[1,4,2],[0,4,1],[0,0,1]])
dA = 1 * 4 * 1
dtA = np.linalg.det(A)
print(dA)
print(round(dtA))

4
4


8. Apabila suatu matriks dikenai suatu Operasi Baris Elementer maka tidak mengubah hasil determinan matriks tersebut

In [11]:
A = np.array([[1,4,2],[1,1,1],[3,2,1]])
B = RowAdd(A,0,1,-1)
DA = np.linalg.det(A)
DB = np.linalg.det(B)
print(round(DA))
print(round(DB))

5
5


9. Apabila suatu matriks ditransposekan maka determinan dari tranpose matriks tersebut adalah determinan dari matriks itu sendiri

In [12]:
AT = np.transpose(A)
DAT = np.linalg.det(AT)
print(A)
print(AT)
print(round(DAT))

[[1 4 2]
 [1 1 1]
 [3 2 1]]
[[1 1 3]
 [4 1 2]
 [2 1 1]]
5
