In [23]:
import numpy as np
A = np.array ([[1, 3, 4], [2, 1, 5]])
B = np.array ([[3, 0, 4], [-1, -2, -1]])
C = np.array ([[2, 8, 7], [6, 5, 2]])
D = np.array ([[12, 4]])
print(C)

[[2 8 7]
 [6 5 2]]


In [ ]:
A @ C = I


In [ ]:
A = np.random.randint(10, size=(3,3))
print(A)

[[7 1 6]
 [5 6 3]
 [4 7 0]]


# Operasi Bilangan Matriks
c = 2\
d = 4\
(c+d)A = cA + dA\
c(dA) = (cd)A


In [ ]:
c = 4
d = 2
hasil = (c + d) * A
print(hasil)

[[42  6 36]
 [30 36 18]
 [24 42  0]]


In [ ]:
e = c * d 
f = e * A
g = c * A
h = d * A
j = c * A + d * A
print(e)
print(f)
print(g)
print(h)
print(j)

8
[[56  8 48]
 [40 48 24]
 [32 56  0]]
[[28  4 24]
 [20 24 12]
 [16 28  0]]
[[14  2 12]
 [10 12  6]
 [ 8 14  0]]
[[42  6 36]
 [30 36 18]
 [24 42  0]]


In [ ]:
G = (c + d) * A
H = (c * A) + (d * A)
print (G)
print (H)

[[42  6 36]
 [30 36 18]
 [24 42  0]]
[[42  6 36]
 [30 36 18]
 [24 42  0]]


In [ ]:
G = (c + d) * A
H = (c * A) + (d * A)
print(G)
print(H)

[[42  6 36]
 [30 36 18]
 [24 42  0]]
[[42  6 36]
 [30 36 18]
 [24 42  0]]


In [ ]:
C.shape[0]

2

In [ ]:
C.shape[1]

3

In [26]:
np.transpose (A)

array([[1, 2],
       [3, 1],
       [4, 5]])

# Mengalikan Matriks dengan Program

# Program Perkalian Matriks

# Matriks Transpose

In [27]:
A = np.array([[5, 4, 0],[1,8,3],[6,7,2]])
A_T = A.transpose()
print(A)
print('\n')
print(A_T)

[[5 4 0]
 [1 8 3]
 [6 7 2]]


[[5 1 6]
 [4 8 7]
 [0 3 2]]


In [28]:
C = A * A_T
C_T = C.transpose()
COV = C * C_T
print(COV)
print(COV.shape)

[[ 625   16    0]
 [  16 4096  441]
 [   0  441   16]]
(3, 3)


In [29]:
A = np.array([[2,1],[1,2]])
A_T = A.transpose()
print(A)
print(A_T) 

[[2 1]
 [1 2]]
[[2 1]
 [1 2]]


In [30]:
M = np.array ([[10, 3, 5], [3, 7, 9], [5, 9, 12]])
M_T = M.transpose()
print(M)
print(M_T)

[[10  3  5]
 [ 3  7  9]
 [ 5  9 12]]
[[10  3  5]
 [ 3  7  9]
 [ 5  9 12]]
